### ISSUE TITLE
Read the docs build broken

### ISSUE THREAD

**Issue by piccolbo** [piccolbo/altair_recipes#3]

**Comment by piccolbo** [comment]
`Running Sphinx v1.7.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 167, in __init__
    raise ConfigError(CONFIG_ERROR % traceback.format_exc())
ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 25, in <module>
    import altair_recipes
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/checkouts/latest/altair_recipes/__init__.py", line 3, in <module>
    from .autocorrelation import autocorrelation
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/checkouts/latest/altair_recipes/autocorrelation.py", line 2, in <module>
    import altair as alt
ImportError: No module named altair


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 25, in <module>
    import altair_recipes
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/checkouts/latest/altair_recipes/__init__.py", line 3, in <module>
    from .autocorrelation import autocorrelation
  File "/home/docs/checkouts/readthedocs.org/user_builds/altair-recipes/checkouts/latest/altair_recipes/autocorrelation.py", line 2, in <module>
    import altair as alt
ImportError: No module named altair
Command `

**Comment by piccolbo** [comment]
Fixed by ae56902
